using InstagramApiTrail.Helpers;
using InstagramApiTrail.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InstagramApiTrail.Controllers
{
    public class InstagramController : Controller
    {
        // GET: Instagram
        //public ActionResult Index()
        //{
            
        //    var service = new SocialFeedService();
        //    var result = service.GetInstagramContents(token);
        //}

            public ActionResult Index()
        {
           
            string token = @"IGQXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            var service = new SocialFeedService();

            // Provide token generated by instagram test user
             IEnumerable<InstagramMediaContent> result=  service.GetInstagramContents(token);
            ViewBag.img = result;

            return View(result);
        }
    }
}






//var service = new SocialFeedService();
//IEnumerable<InstagramMediaContent> result = service.GetInstagramContents(token);

// To Refresh the Instagram Token
//string tokenExpiry = service.RefreshToken(token);